version: '2'

volumes:
  nextcloud:
  db:
  wordpress:
  db2:

secrets:
  pass_mysql_root:
    file: ./pass_mysql_root.txt
  pass_mysql:
    file: ./pass_mysql.txt
  pass_mysql_website:
    file: ./pass_mysql_website.txt
  pass_mysql_root_website:
    file: ./pass_mysql_root_website.txt

networks:
  file_server_net:
    name: file_server_vnet
    driver: bridge
  website_net:
    name: website_vnet
    driver: bridge

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/pass_mysql_root
      - MYSQL_PASSWORD=/run/secrets/pass_mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user_ek
    secrets:
      - pass_mysql_root
      - pass_mysql
    networks:
      - file_server_net

  app:
    build: .
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=/run/secrets/pass_mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user_ek
      - MYSQL_HOST=db
    secrets:
      - pass_mysql
    networks:
      - file_server_net

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 5000:80
    environment:
      - WORDPRESS_DB_HOST= db2
      - WORDPRESS_DB_USER= user_dui
      - WORDPRESS_DB_PASSWORD= /run/secrets/pass_mysql_website
      - WORDPRESS_DB_NAME= exampledb
    volumes:
      - wordpress:/var/www/html
    networks:
      - website_net

  db2:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE = exampledb
      - MYSQL_USER = user_dui
      - MYSQL_PASSWORD = /run/secrets/pass_mysql_website
      - MYSQL_ROOT_PASSWORD=  /run/secrets/pass_mysql_root_website
    volumes:
      - db2:/var/lib/mysql
    networks:
      - website_net